#88888888ba                           88                              88888888ba   88
#88      "8b                          ""                              88      "8b  88
#88      ,8P                                                          88      ,8P  88
#88aaaaaa8P'  ,adPPYba,  8b       d8  88  8b       d8   ,adPPYba,     88aaaaaa8P'  88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,
#88""""88'   a8P_____88  `8b     d8'  88  `8b     d8'  a8P_____88     88""""""'    88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8
#88    `8b   8PP"""""""   `8b   d8'   88   `8b   d8'   8PP"""""""     88           88  ,adPPPPP88   `8b   d8'   8PP"""""""  88
#88     `8b  "8b,   ,aa    `8b,d8'    88    `8b,d8'    "8b,   ,aa     88           88  88,    ,88    `8b,d8'    "8b,   ,aa  88
#88      `8b  `"Ybbd8"'      "8"      88      "8"       `"Ybbd8"'     88           88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88



#Set the time in seconds
time: 120

#If set to true, the /kill command will kill the player instantly, but if set to false, the player will bleed.
kill_enable: false

#Set the player's remaining life
bleeding_health_level: 6

#Set the player's remaining food
bleeding_food_level: 6

#Set the language, you can add your own by copying and editing the "en" file in the lang folder, put the name of the file
#Spanish (es) and English (en) languages are now available
lang: "en"


#Don't modify
ver: "1.0"