#88888888ba                           88                              88888888ba   88
#88      "8b                          ""                              88      "8b  88
#88      ,8P                                                          88      ,8P  88
#88aaaaaa8P'  ,adPPYba,  8b       d8  88  8b       d8   ,adPPYba,     88aaaaaa8P'  88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,
#88""""88'   a8P_____88  `8b     d8'  88  `8b     d8'  a8P_____88     88""""""'    88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8
#88    `8b   8PP"""""""   `8b   d8'   88   `8b   d8'   8PP"""""""     88           88  ,adPPPPP88   `8b   d8'   8PP"""""""  88
#88     `8b  "8b,   ,aa    `8b,d8'    88    `8b,d8'    "8b,   ,aa     88           88  88,    ,88    `8b,d8'    "8b,   ,aa  88
#88      `8b  `"Ybbd8"'      "8"      88      "8"       `"Ybbd8"'     88           88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88

#If you don't enable PlaceHolderAPI, use %name% to set player name
#You can use & to set colors

#Set the time in seconds
time: 120

kill_enable: false

keep_inventory: false

enable_papi: false

lang: "en"
#Dont modifcate
ver: 0.1